{
 "cells": [
  {
   "cell_type": "code",
   "id": "initial_id",
   "metadata": {
    "collapsed": true,
    "ExecuteTime": {
     "end_time": "2025-12-08T06:43:56.809840Z",
     "start_time": "2025-12-08T06:43:56.804337Z"
    }
   },
   "source": [
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "from typing import Dict, Any, Union, Tuple\n",
    "from math import radians, sin, cos, asin, sqrt\n"
   ],
   "outputs": [],
   "execution_count": 4
  },
  {
   "metadata": {
    "ExecuteTime": {
     "end_time": "2025-12-10T13:09:06.811598Z",
     "start_time": "2025-12-10T13:09:05.939258Z"
    }
   },
   "cell_type": "code",
   "source": [
    "\n",
    "def load_traffic_tensor(output_dir: Union[str, Path]) -> Dict[str, Any]:\n",
    "    output_dir = Path(output_dir)\n",
    "    tensor_path = output_dir / \"traffic_tensor.npz\"\n",
    "    data = np.load(tensor_path)\n",
    "\n",
    "    values = data[\"values\"].astype(\"float32\")\n",
    "    segment_ids = data[\"segment_ids\"]\n",
    "    return {\n",
    "        \"values\": values,\n",
    "        \"segment_ids\": segment_ids,\n",
    "    }\n",
    "# ============================================================\n",
    "# 1) Pearson time-lag cross-correlation cho một cặp (i, j)\n",
    "# ============================================================\n",
    "def cross_corr_time_lag_pair(\n",
    "    x: np.ndarray,y:np.ndarray,tau_max:int\n",
    ") -> Tuple[np.ndarray,np.ndarray]:\n",
    "    assert x.ndim == 1 and y.ndim == 1\n",
    "    assert len(x) == len(y)\n",
    "    L = len(x)\n",
    "    taus = np.arange(-tau_max, tau_max + 1, dtype=int)\n",
    "    corrs = np.zeros_like(taus,dtype=np.float32)\n",
    "\n",
    "    def _pearson(a: np.ndarray, b: np.ndarray) -> float:\n",
    "        if a.size < 2:\n",
    "            return 0.0\n",
    "        a_mean = a.mean()\n",
    "        b_mean = b.mean()\n",
    "        a_centered = a - a_mean\n",
    "        b_centered = b - b_mean\n",
    "\n",
    "        num = np.sum(a_centered * b_centered)\n",
    "        den = np.sqrt(np.sum(a_centered**2) * np.sum(b_centered**2))\n",
    "        if den <= 1e-12:\n",
    "            return 0.0\n",
    "        return float(num / den)\n",
    "    for k, tau in enumerate(taus):\n",
    "        if tau == 0:\n",
    "            a = x\n",
    "            b = y\n",
    "        elif tau > 0:\n",
    "            a = x[: L - tau]\n",
    "            b = y[tau:]\n",
    "        else:\n",
    "            lag = -tau\n",
    "            a = y[: L - lag]\n",
    "            b = x[lag:]\n",
    "        corrs[k] = _pearson(a, b)\n",
    "    return taus, corrs\n",
    "\n",
    "# ============================================================\n",
    "# 2) Link weight W^{pos}_{i,j} như paper\n",
    "# ============================================================\n",
    "\n",
    "def link_weight_pos(x: np.ndarray,y: np.ndarray,tau_max: int) -> Tuple[float, int, float]:\n",
    "    taus, corrs = cross_corr_time_lag_pair(x, y, tau_max)\n",
    "    max_corr = float(np.max(corrs))\n",
    "    tau_peak = int(taus[np.argmax(corrs)])\n",
    "    mean_corr = float(np.mean(corrs))\n",
    "    std_corr = float(np.std(corrs))\n",
    "    if std_corr < 1e-6:\n",
    "        std_corr = 1e-6\n",
    "    Wpos = (max_corr - mean_corr) / std_corr\n",
    "    return float(Wpos), tau_peak, max_corr\n",
    "\n",
    "def compute_anchor_correlations(\n",
    "    output_dir: Union[str, Path],\n",
    "    anchor_segment_id: Union[int, str],\n",
    "    tau_max: int = 3,\n",
    ") -> Dict[str, Any]:\n",
    "    \"\"\"\n",
    "    Tính link weight W^{pos}_{anchor, j} giữa 1 anchor và toàn bộ segments.\n",
    "    \"\"\"\n",
    "    data = load_traffic_tensor(output_dir)\n",
    "    values = data[\"values\"]            # (T, N)\n",
    "    segment_ids = data[\"segment_ids\"]  # (N,)\n",
    "\n",
    "    # tìm index anchor trong segment_ids\n",
    "    mask = (segment_ids == anchor_segment_id)\n",
    "    idx_arr = np.where(mask)[0]\n",
    "    if len(idx_arr) == 0:\n",
    "        raise ValueError(f\"Anchor segment_id {anchor_segment_id} not found in segment_ids.\")\n",
    "    anchor_idx = int(idx_arr[0])\n",
    "\n",
    "    x = values[:, anchor_idx]  # (T,)\n",
    "\n",
    "    T, N = values.shape\n",
    "    weights = np.zeros(N, dtype=np.float32)\n",
    "    tau_peaks = np.zeros(N, dtype=np.int32)\n",
    "    max_corrs = np.zeros(N, dtype=np.float32)\n",
    "\n",
    "    for j in range(N):\n",
    "        if j == anchor_idx:\n",
    "            # self-link\n",
    "            weights[j] = 0.0\n",
    "            tau_peaks[j] = 0\n",
    "            max_corrs[j] = 1.0\n",
    "            continue\n",
    "\n",
    "        y = values[:, j]  # (T,)\n",
    "        Wpos, tau_peak, max_corr = link_weight_pos(x, y, tau_max=tau_max)\n",
    "\n",
    "        weights[j] = Wpos\n",
    "        tau_peaks[j] = tau_peak\n",
    "        max_corrs[j] = max_corr\n",
    "\n",
    "    return {\n",
    "        \"anchor_segment_id\": anchor_segment_id,\n",
    "        \"segment_ids\": segment_ids,\n",
    "        \"anchor_index\": anchor_idx,\n",
    "        \"weights\": weights,\n",
    "        \"tau_peaks\": tau_peaks,\n",
    "        \"max_corrs\": max_corrs,\n",
    "    }\n",
    "\n",
    "# ============================================================\n",
    "# 3) Haversine distance (m) giữa 2 điểm (lat, lon)\n",
    "# ============================================================\n",
    "def haversine_distance(lat1, lon1, lat2, lon2) -> float:\n",
    "    \"\"\"\n",
    "    lat, lon tính bằng độ. Kết quả trả về mét.\n",
    "    \"\"\"\n",
    "    R = 6371000.0  # bán kính Trái Đất (m)\n",
    "\n",
    "    phi1 = radians(lat1)\n",
    "    phi2 = radians(lat2)\n",
    "    dphi = radians(lat2 - lat1)\n",
    "    dlambda = radians(lon2 - lon1)\n",
    "\n",
    "    a = sin(dphi / 2.0) ** 2 + cos(phi1) * cos(phi2) * sin(dlambda / 2.0) ** 2\n",
    "    c = 2 * asin(sqrt(a))\n",
    "    return float(R * c)\n",
    "\n",
    "\n",
    "def load_node_positions(output_dir: Union[str, Path]) -> Dict[int, Tuple[float, float]]:\n",
    "    \"\"\"\n",
    "    Đọc nodes.csv → map node_id -> (lat, lon)\n",
    "    Giả sử file nằm trong: output_dir / \"tomtom_stats\" / \"nodes.csv\"\n",
    "    \"\"\"\n",
    "    output_dir = Path(output_dir)\n",
    "    nodes_path = output_dir / \"tomtom_stats\" / \"nodes.csv\"\n",
    "    df_nodes = pd.read_csv(nodes_path)\n",
    "\n",
    "    node2pos: Dict[int, Tuple[float, float]] = {}\n",
    "    for _, row in df_nodes.iterrows():\n",
    "        node_id = int(row[\"node_id\"])\n",
    "        lat = float(row[\"lat\"])\n",
    "        lon = float(row[\"lon\"])\n",
    "        node2pos[node_id] = (lat, lon)\n",
    "    return node2pos\n",
    "\n",
    "\n",
    "def load_segment_centers(output_dir: Union[str, Path]) -> Dict[int, Tuple[float, float]]:\n",
    "    \"\"\"\n",
    "    Đọc segments.csv + nodes.csv để tính center (lat, lon)\n",
    "    của mỗi segment_id.\n",
    "\n",
    "    center = midpoint(node_u, node_v) theo lat/lon.\n",
    "    \"\"\"\n",
    "    output_dir = Path(output_dir)\n",
    "    seg_path = output_dir / \"tomtom_stats\" / \"segments.csv\"\n",
    "\n",
    "    df_segments = pd.read_csv(seg_path)\n",
    "    node2pos = load_node_positions(output_dir)\n",
    "\n",
    "    seg2center: Dict[int, Tuple[float, float]] = {}\n",
    "    for _, row in df_segments.iterrows():\n",
    "        seg_id = int(row[\"segment_id\"])\n",
    "        u = int(row[\"node_u\"])\n",
    "        v = int(row[\"node_v\"])\n",
    "\n",
    "        if (u not in node2pos) or (v not in node2pos):\n",
    "            # thiếu thông tin node → bỏ qua (sẽ set NaN sau)\n",
    "            continue\n",
    "\n",
    "        lat_u, lon_u = node2pos[u]\n",
    "        lat_v, lon_v = node2pos[v]\n",
    "        lat_c = (lat_u + lat_v) / 2.0\n",
    "        lon_c = (lon_u + lon_v) / 2.0\n",
    "        seg2center[seg_id] = (lat_c, lon_c)\n",
    "\n",
    "    return seg2center\n",
    "\n",
    "def compute_dist_to_anchor_from_centers(\n",
    "    output_dir: Union[str, Path],\n",
    "    segment_ids_tensor: np.ndarray,\n",
    "    anchor_index: int,\n",
    ") -> np.ndarray:\n",
    "    \"\"\"\n",
    "    Từ segment_ids trong traffic_tensor (segment_ids_tensor),\n",
    "    dùng segments.csv + nodes.csv để tính center (lat, lon),\n",
    "    sau đó tính khoảng cách Haversine từ anchor đến mọi segment.\n",
    "\n",
    "    return:\n",
    "        dist_to_anchor: (N,) mét. Seg nào thiếu center sẽ có dist = +inf.\n",
    "    \"\"\"\n",
    "    seg2center = load_segment_centers(output_dir)\n",
    "\n",
    "    N = len(segment_ids_tensor)\n",
    "    lat_all = np.full(N, np.nan, dtype=\"float32\")\n",
    "    lon_all = np.full(N, np.nan, dtype=\"float32\")\n",
    "\n",
    "    # map theo đúng thứ tự segment_ids_tensor\n",
    "    for i, sid in enumerate(segment_ids_tensor):\n",
    "        sid_int = int(sid)\n",
    "        if sid_int in seg2center:\n",
    "            lat_all[i] = seg2center[sid_int][0]\n",
    "            lon_all[i] = seg2center[sid_int][1]\n",
    "        else:\n",
    "            # thiếu center → giữ NaN\n",
    "            pass\n",
    "\n",
    "    lat_anchor = float(lat_all[anchor_index])\n",
    "    lon_anchor = float(lon_all[anchor_index])\n",
    "\n",
    "    dist_to_anchor = np.full(N, np.inf, dtype=\"float32\")\n",
    "\n",
    "    for j in range(N):\n",
    "        if j == anchor_index:\n",
    "            dist_to_anchor[j] = 0.0\n",
    "            continue\n",
    "        if np.isnan(lat_all[j]) or np.isnan(lon_all[j]):\n",
    "            # không có center → coi như rất xa\n",
    "            dist_to_anchor[j] = np.inf\n",
    "            continue\n",
    "\n",
    "        d = haversine_distance(\n",
    "            lat_anchor, lon_anchor,\n",
    "            float(lat_all[j]), float(lon_all[j])\n",
    "        )\n",
    "        dist_to_anchor[j] = d\n",
    "\n",
    "    return dist_to_anchor  # (N,) mét\n",
    "\n",
    "def build_influenced_subgraph(\n",
    "    output_dir: Union[str, Path],\n",
    "    corr_info: Dict[str, Any],\n",
    "    tau_cut: int = 40,\n",
    "    Wmin: float = None,\n",
    "    Dmax: float = None,\n",
    "    top_k: int = 30,\n",
    ") -> Dict[str, Any]:\n",
    "    \"\"\"\n",
    "    Lọc các tuyến có khả năng bị anchor ảnh hưởng, dùng:\n",
    "      - |tau_peak| <= tau_cut\n",
    "      - Wpos >= Wmin  (nếu Wmin=None thì lấy theo percentile 80%)\n",
    "      - dist_to_anchor <= Dmax (mét; nếu Dmax=None thì lấy theo percentile 80%)\n",
    "\n",
    "    Sau đó sort theo Wpos giảm dần và lấy top_k neighbor.\n",
    "    \"\"\"\n",
    "    output_dir = Path(output_dir)\n",
    "\n",
    "    anchor_segment_id = corr_info[\"anchor_segment_id\"]\n",
    "    segment_ids = corr_info[\"segment_ids\"]\n",
    "    anchor_idx = int(corr_info[\"anchor_index\"])\n",
    "    weights = corr_info[\"weights\"]\n",
    "    tau_peaks = corr_info[\"tau_peaks\"]\n",
    "    max_corrs = corr_info[\"max_corrs\"]\n",
    "\n",
    "    # 1) khoảng cách (Haversine) tới anchor, theo thứ tự segment_ids\n",
    "    dist_to_anchor = compute_dist_to_anchor_from_centers(\n",
    "        output_dir, segment_ids, anchor_idx\n",
    "    )  # (N,) mét\n",
    "\n",
    "    # 2) lọc theo |tau_peak|\n",
    "    mask = np.abs(tau_peaks) <= tau_cut\n",
    "\n",
    "    W_candidates = weights[mask]\n",
    "    tau_candidates = tau_peaks[mask]\n",
    "    corr_candidates = max_corrs[mask]\n",
    "    dist_candidates = dist_to_anchor[mask]\n",
    "    idx_candidates = np.arange(len(segment_ids))[mask]\n",
    "\n",
    "    if W_candidates.size == 0:\n",
    "        raise RuntimeError(\"Không có candidate nào sau khi lọc theo tau_cut.\")\n",
    "\n",
    "    # 3) nếu chưa set Wmin/Dmax thì lấy theo percentile\n",
    "    if Wmin is None:\n",
    "        Wmin = float(np.percentile(W_candidates, 70))   # top 30% mạnh nhất\n",
    "    if Dmax is None:\n",
    "        # ví dụ, chỉ lấy 80% gần nhất theo Haversine\n",
    "        Dmax = float(np.percentile(dist_candidates[np.isfinite(dist_candidates)], 70))\n",
    "\n",
    "    mask2 = (W_candidates >= Wmin) & (dist_candidates <= Dmax)\n",
    "\n",
    "    W_sel = W_candidates[mask2]\n",
    "    tau_sel = tau_candidates[mask2]\n",
    "    corr_sel = corr_candidates[mask2]\n",
    "    dist_sel = dist_candidates[mask2]\n",
    "    idx_sel = idx_candidates[mask2]\n",
    "\n",
    "    # bỏ anchor nếu lỡ dính\n",
    "    idx_sel = idx_sel[idx_sel != anchor_idx]\n",
    "\n",
    "    if idx_sel.size == 0:\n",
    "        raise RuntimeError(\"Không còn neighbor nào sau khi áp Wmin/Dmax, hãy giảm ngưỡng.\")\n",
    "\n",
    "    # 4) sort theo Wpos giảm dần\n",
    "    order = np.argsort(-W_sel)\n",
    "    W_sel = W_sel[order]\n",
    "    tau_sel = tau_sel[order]\n",
    "    corr_sel = corr_sel[order]\n",
    "    dist_sel = dist_sel[order]\n",
    "    idx_sel = idx_sel[order]\n",
    "\n",
    "    # 5) lấy top_k\n",
    "    if top_k is not None and idx_sel.size > top_k:\n",
    "        W_sel = W_sel[:top_k]\n",
    "        tau_sel = tau_sel[:top_k]\n",
    "        corr_sel = corr_sel[:top_k]\n",
    "        dist_sel = dist_sel[:top_k]\n",
    "        idx_sel = idx_sel[:top_k]\n",
    "\n",
    "    neighbor_indices = idx_sel\n",
    "    neighbor_segment_ids = segment_ids[neighbor_indices]\n",
    "    selected_indices = np.concatenate([[anchor_idx], neighbor_indices])\n",
    "\n",
    "    return {\n",
    "        \"anchor_segment_id\": anchor_segment_id,\n",
    "        \"anchor_index\": anchor_idx,\n",
    "        \"segment_ids\": segment_ids,\n",
    "        \"selected_indices\": selected_indices,\n",
    "        \"neighbor_segment_ids\": neighbor_segment_ids,\n",
    "        \"neighbor_indices\": neighbor_indices,\n",
    "        \"Wpos\": W_sel,\n",
    "        \"tau_peaks\": tau_sel,\n",
    "        \"max_corrs\": corr_sel,\n",
    "        \"dist_to_anchor\": dist_sel,      # mét\n",
    "        \"Wmin_used\": Wmin,\n",
    "        \"Dmax_used\": Dmax,\n",
    "    }\n",
    "\n",
    "def build_laplacian_from_distance(\n",
    "    subgraph_info: Dict[str, Any],\n",
    "    d_spa: int = 16,\n",
    "    sigma: float = 500.0,\n",
    ") -> Dict[str, Any]:\n",
    "    \"\"\"\n",
    "    Xây adjacency + Laplacian eigenvectors cho subgraph\n",
    "    dùng khoảng cách Haversine tới anchor (mét):\n",
    "\n",
    "      - node 0: anchor\n",
    "      - node 1..k: neighbors\n",
    "      - A[0,i] = A[i,0] = exp(-dist_i / sigma)\n",
    "\n",
    "    sigma: tham số scale (m). Ví dụ:\n",
    "      - 500 → edge weight ~0.37 tại 500m\n",
    "      - 1000 → edge weight ~0.37 tại 1km\n",
    "    \"\"\"\n",
    "    dist_to_anchor = subgraph_info[\"dist_to_anchor\"]  # (k,) mét\n",
    "    k = dist_to_anchor.shape[0]\n",
    "    n_nodes = k + 1\n",
    "\n",
    "    A = np.zeros((n_nodes, n_nodes), dtype=\"float32\")\n",
    "    for i in range(1, n_nodes):\n",
    "        d = float(dist_to_anchor[i - 1])  # mét\n",
    "        w = float(np.exp(-d / sigma))\n",
    "        A[0, i] = w\n",
    "        A[i, 0] = w\n",
    "\n",
    "    d_vec = A.sum(axis=1)\n",
    "    D = np.diag(d_vec)\n",
    "    L = D - A\n",
    "\n",
    "    evals, evecs = np.linalg.eigh(L)\n",
    "    idx = np.argsort(evals)\n",
    "    if d_spa < n_nodes:\n",
    "        idx = idx[:d_spa]\n",
    "    lap_eigvec = evecs[:, idx].astype(\"float32\")  # (n_nodes, d_spa)\n",
    "\n",
    "    out = dict(subgraph_info)\n",
    "    out.update({\n",
    "        \"adjacency\": A,\n",
    "        \"lap_eigvec\": lap_eigvec,\n",
    "    })\n",
    "    return out\n",
    "\n",
    "\n"
   ],
   "id": "8a1e17367388fc83",
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'Union' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001B[1;31m---------------------------------------------------------------------------\u001B[0m",
      "\u001B[1;31mNameError\u001B[0m                                 Traceback (most recent call last)",
      "Cell \u001B[1;32mIn[1], line 1\u001B[0m\n\u001B[1;32m----> 1\u001B[0m \u001B[38;5;28;01mdef\u001B[39;00m\u001B[38;5;250m \u001B[39m\u001B[38;5;21mload_traffic_tensor\u001B[39m(output_dir: \u001B[43mUnion\u001B[49m[\u001B[38;5;28mstr\u001B[39m, Path]) \u001B[38;5;241m-\u001B[39m\u001B[38;5;241m>\u001B[39m Dict[\u001B[38;5;28mstr\u001B[39m, Any]:\n\u001B[0;32m      2\u001B[0m     output_dir \u001B[38;5;241m=\u001B[39m Path(output_dir)\n\u001B[0;32m      3\u001B[0m     tensor_path \u001B[38;5;241m=\u001B[39m output_dir \u001B[38;5;241m/\u001B[39m \u001B[38;5;124m\"\u001B[39m\u001B[38;5;124mtraffic_tensor.npz\u001B[39m\u001B[38;5;124m\"\u001B[39m\n",
      "\u001B[1;31mNameError\u001B[0m: name 'Union' is not defined"
     ]
    }
   ],
   "execution_count": 1
  },
  {
   "metadata": {},
   "cell_type": "code",
   "outputs": [],
   "execution_count": null,
   "source": "",
   "id": "546f6f8c3a97bf3c"
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 2
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython2",
   "version": "2.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
